// apps/web/src/features/user/components/LoginForm.vue
<script setup lang="ts">
import { reactive, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { Icon } from '@iconify/vue';
import { UserInterface } from '@flowx/shared';
import { PassKey, SignIn } from 'app/assets/icons';
import { VInputLabel } from 'app/components';

const props = defineProps<{
  onSubmit: (data: UserInterface) => void;
}>();

const { t } = useI18n();
const hasError = ref(false);
const formData = reactive<UserInterface & { rememberMe: boolean }>({
  email: '',
  password: '',
  rememberMe: false,
});

const handleSubmit = (ev: Event) => {
  ev.preventDefault();

  props.onSubmit(formData);
};
</script>

<template>
  <form method="POST" action="/" @submit="handleSubmit">
    <div class="form-control gap-2">
      <VInputLabel
        id="email"
        :label="t('user.authenticate.email')"
        input-type="email"
        v-model="formData.email"
        autocomplete="email"
        required
        :placeholder="t('placeholder.email')"
        :show-error="hasError"
        :error-message="t('error.userAlreadyExists')"
      />

      <VInputLabel
        id="password"
        :label="t('user.authenticate.password')"
        input-type="password"
        v-model="formData.password"
        minlength="8"
        autocomplete="new-password"
        required
        :show-error="hasError"
        :error-message="t('error.incorrectPassword')"
      />

      <div class="block text-right">
        <button class="btn btn-sm btn-link" type="button">{{ t('user.authenticate.recoverPassword') }}</button>
      </div>

      <button class="btn btn-primary" type="submit">
        <Icon :icon="SignIn" height="20" />
        {{ t('button.login') }}
      </button>
    </div>
  </form>

  <span class="h-1px my-6 w-full border-t border-gray-700"></span>

  <button class="btn btn-outline" type="submit">
    <Icon :icon="PassKey" height="20" />
    <span class="hidden md:block">{{ t('user.authenticate.loginWith.passkeys') }}</span>
  </button>
</template>

// apps/web/app/features/auth/components/LoginForm.tsx
import { PropsWithoutRef } from 'react';
import { useForm } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { PassKey } from '@/assets/icons';
import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Separator } from '@/components/ui/separator';
import { typeboxResolver } from '@hookform/resolvers/typebox';
import { UserLoginForm } from '@flowx/shared/models/user';

type Props = {
  onSubmit: (data: UserLoginForm) => void;
  toggleMode: () => void;
};

const LoginForm = ({ onSubmit, toggleMode }: PropsWithoutRef<Props>) => {
  const { t } = useTranslation('User');

  const form = useForm<UserLoginForm>({
    resolver: typeboxResolver(UserLoginForm),
    defaultValues: {
      login: '',
      password: '',
    },
  });

  return (
    <>
      <Button>
        <PassKey height={20} />
        <span className="hidden md:ml-2 md:block">{t('Sign in with Passkeys')}</span>
      </Button>

      <Separator className="mb-6 mt-8 " />

      <Form {...form}>
        <form
          onSubmit={(event) => {
            void form.handleSubmit(onSubmit)(event);
          }}
          className="flex flex-col gap-6"
        >
          <FormField
            control={form.control}
            name="login"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t('Email')}</FormLabel>
                <FormControl>
                  <Input placeholder="Email..." {...field} />
                </FormControl>
                <FormDescription>{t('Your email address used to login into app')}</FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t('Password')}</FormLabel>
                <FormControl>
                  <Input {...field} />
                </FormControl>
                <FormDescription>
                  {t('Your super secret password that will allow you to use the app')}
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <Button type="submit">{t('Login')}</Button>

          <div className="block text-right">
            <Button type="button" variant="link" onClick={toggleMode}>
              {t("Don't have account? Sign up!")}
            </Button>
          </div>
        </form>
      </Form>
    </>
  );
};

export default LoginForm;
