// apps/web/src/pages/Error/NotFound.vue
<script setup lang="ts">
import { ArrowLeft } from 'app/assets/icons';
import VButton from 'ui/VButton.vue';

const router = useRouter();

const goBackBtn = () => {
  router.push({ name: 'Home' });
};
</script>

<template>
  <div class="m-auto flex h-screen w-screen items-center justify-center">
    <div class="flex flex-col items-center gap-8">
      <h3 class="text-5xl"><span class="text-sky-700">[404]</span> Looks like we are missing a page</h3>

      <VButton class="text-lg" @click="goBackBtn"> <ArrowLeft class="mr-2" /> Go back </VButton>
    </div>
  </div>
</template>

// apps/web/src/components/pages/NotFound.tsx
import { useNavigate } from 'react-router-dom';

import { ArrowLeft } from 'app/assets/icons';

import { Button } from 'ui/button';

const NotFound = () => {
  const navigate = useNavigate();
  const goBackBtn = () => navigate('/');

  return (
    <div className="m-auto flex h-screen w-screen items-center justify-center">
      <div className="flex flex-col items-center gap-8">
        <h3 className="text-5xl">
          <span className="text-sky-700">[404]</span> Looks like we are missing a page
        </h3>

        <Button className="text-lg" onClick={goBackBtn}>
          <ArrowLeft className="mr-2" /> Go back
        </Button>
      </div>
    </div>
  );
};

export default NotFound;
