// apps/web/src/features/user/views/Authenticate.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { UserInterface, UserRegisterInterface } from '@flowx/shared';
import { LoginForm, RegisterForm } from '../components';

const { t } = useI18n();

const loginMode = ref(true);
const authenticationModeTitle = computed(() =>
  loginMode.value ? t('user.authenticate.login') : t('user.authenticate.register'),
);

const handleLogin = (ev: UserInterface) => {
  console.log(ev);
};

const handleRegister = (ev: UserRegisterInterface) => {
  console.log(ev);
};

const toggleMode = () => {
  loginMode.value = !loginMode.value;
};
</script>

<template>
  <div className="m-auto h-full max-w-lg p-5 pt-2 flex flex-col justify-center">
    <h1 class="mb-6 text-center text-4xl font-bold">{{ authenticationModeTitle }}</h1>

    <LoginForm v-if="loginMode" :onSubmit="handleLogin" :toggle-mode="toggleMode"></LoginForm>
    <RegisterForm v-else :onSubmit="handleRegister" :toggle-mode="toggleMode"></RegisterForm>
  </div>
</template>

// apps/web/src/features/auth/views/Authenticate.tsx
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';

import AuthenticateLayout from 'app/components/layouts/AuthenticateLayout';
import { UserFormModel, UserRegisterFormModel } from 'app/features/user/models/user.model';

import LoginForm from '../components/LoginForm';
import RegisterForm from '../components/RegisterForm';

const Authenticate = () => {
  const { t } = useTranslation(['user']);

  const [loginMode, setLoginMode] = useState(true);
  const modeTitle = useMemo(() => (loginMode ? t('Login') : t('Register')), [loginMode]);

  const handleLogin = (ev: UserFormModel) => {
    console.log(ev);
  };

  const handleRegister = (ev: UserRegisterFormModel) => {
    console.log(ev);
  };

  const toggleMode = () => {
    setLoginMode(!loginMode);
  };

  return (
    <AuthenticateLayout>
      <div className="m-auto flex w-full max-w-lg flex-col justify-center p-5 pt-2">
        <h1 className="mb-12 text-center text-4xl font-bold">{modeTitle}</h1>

        {loginMode ? (
          <LoginForm onSubmit={handleLogin} toggleMode={toggleMode} />
        ) : (
          <RegisterForm onSubmit={handleRegister} toggleMode={toggleMode} />
        )}
      </div>
    </AuthenticateLayout>
  );
};

export default Authenticate;
