// packages/web/app/features/auth/components/LoginForm.tsx
import { PropsWithoutRef } from 'react';
import { useForm } from 'react-hook-form';
import { useTranslation } from 'react-i18next';
import { typeboxResolver } from '@hookform/resolvers/typebox';
import { UserLoginForm } from '@flowx/shared/models/user';
import { PassKey } from 'app/assets/icons';
import { Button } from 'app/components/ui/button';
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from 'app/components/ui/form';
import { Input } from 'app/components/ui/input';
import { Separator } from 'app/components/ui/separator';

type Props = {
  onSubmit: (data: UserLoginForm) => void;
  toggleMode: () => void;
};

const LoginForm = ({ onSubmit, toggleMode }: PropsWithoutRef<Props>) => {
  const { t } = useTranslation('User');

  const form = useForm<UserLoginForm>({
    resolver: typeboxResolver(UserLoginForm),
    defaultValues: {
      login: '',
      password: '',
    },
  });

  return (
    <>
      <Button>
        <PassKey height={20} />
        <span className="hidden md:ml-2 md:block">{t('Sign in with Passkeys')}</span>
      </Button>

      <Separator className="mb-6 mt-8 " />

      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col gap-6">
          <FormField
            control={form.control}
            name="login"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t('Email')}</FormLabel>
                <FormControl>
                  <Input placeholder="Email..." {...field} />
                </FormControl>
                <FormDescription>{t('Your email address used to login into app')}</FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t('Password')}</FormLabel>
                <FormControl>
                  <Input {...field} />
                </FormControl>
                <FormDescription>
                  {t('Your super secret password that will allow you to use the app')}
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <Button type="submit">{t('Login')}</Button>

          <div className="block text-right">
            <Button type="button" variant="link" onClick={toggleMode}>
              {t("Don't have account? Sign up!")}
            </Button>
          </div>
        </form>
      </Form>
    </>
  );
};

export default LoginForm;

// apps/web/src/features/auth/components/LoginForm.vue
<script setup lang="ts">
import { UserInterface } from '@flowx/shared';
import { PassKey } from 'app/assets/icons';
import VButton from 'ui/VButton.vue';
import VInputLabel from 'ui/VInputLabel.vue';

const { t } = useI18n();

const props = defineProps<{
  onSubmit: (data: UserInterface) => void;
  toggleMode: () => void;
}>();

const formData = reactive<UserInterface>({
  email: '',
  password: '',
});

const handleSubmit = (ev: Event) => {
  ev.preventDefault();

  props.onSubmit(formData);
};
</script>

<template>
  <VButton outline>
    <PassKey height="20" />
    <span className="hidden md:ml-2 md:block">{{ t('auth.sign_in_with_passkeys') }}</span>
  </VButton>

  <!-- <Separator className="mb-6 mt-8 " /> -->

  <span class="h-1px mb-6 mt-10 w-full border-t border-gray-700" />

  <form method="POST" action="/" @submit="handleSubmit">
    <div class="form-control gap-4">
      <VInputLabel
        id="email"
        v-model="formData.email"
        type="email"
        :label="t('auth.email')"
        autocomplete="email"
        required
        :placeholder="t('placeholder.email')"
      />

      <VInputLabel
        id="password"
        v-model="formData.password"
        type="password"
        :label="t('auth.password')"
        minlength="8"
        autocomplete="new-password"
        required
      />

      <!-- <div class="block text-right">
        <VButton variant="ghost">
          {{ t('user.authenticate.recoverPassword') }}
        </VButton>
      </div> -->

      <VButton type="submit" variant="primary" class="mt-2">
        {{ t('auth.login') }}
      </VButton>

      <div class="block text-right">
        <VButton type="button" variant="link" @click="toggleMode">
          {{ t(`auth.dont_have_account_sign_up`) }}
        </VButton>
      </div>
    </div>
  </form>
</template>
