// apps/web/src/components/layouts/MainLayout.tsx
import { PropsWithChildren } from 'react';

import Sidebar from 'app/components/Sidebar/Sidebar';

const MainLayout = ({ children }: PropsWithChildren) => {
  return (
    <div className="flex h-screen w-screen flex-row gap-6 font-sans text-base antialiased transition-colors">
      <Sidebar openSidebar className="flex-1" />

      <div className="flex-1">{children}</div>
    </div>
  );
};

export default MainLayout;

// apps/web/src/layouts/MainLayout.vue
<script setup lang="ts">
import Sidebar from 'app/components/Sidebar/VSidebar.vue';
</script>

<template>
  <div class="flex h-screen w-screen flex-row gap-6 font-sans text-base antialiased transition-colors">
    <Sidebar openSidebar class="flex-1" />

    <div class="flex-1">
      <slot></slot>
    </div>
  </div>
</template>
